LOG_LEVEL := "debug"

test:
    env RUST_BACKTRACE=1 RUST_LOG={{LOG_LEVEL}} cargo test --no-default-features --features=bloom-filters

lint:
    cargo clippy --no-default-features -- -D warnings

check-formatting:
    cargo fmt --check

fix-formatting:
    cargo fmt

udeps:
    cargo udeps --all-targets --release

wisckey-test:
    env RUST_BACKTRACE=1 RUST_LOG={{LOG_LEVEL}} cargo test --no-default-features --features=snappy-compression,wisckey
